.github/workflows/build_workflow.yml, .pre-commit-config.yaml, deploy/dev-spec.txt, setup.cfg
This merge adds
* pre-commit checks with:
* isort 
* flake8
* mypy
* a beginning of a development environment
* a github action to perform pre-commit checks
=> Add pre-commit checks

docs/_static/style.css, docs/_templates/layout.html, docs/_templates/versions.html, docs/conf.py
...missing so far as @tomvothecoder pointed out.
=> Add versions side bar

deploy/conda-dev-spec.template, docs/.gitignore, docs/Makefile, docs/conf.py, docs/developers_guide/api.md, docs/developers_guide/machines/anvil.md, docs/developers_guide/machines/chicoma.md, docs/developers_guide/machines/chrysalis.md, docs/developers_guide/machines/compy.md, docs/developers_guide/machines/cori.md, docs/developers_guide/machines/index.md, docs/developers_guide/machines/perlmutter.md, docs/developers_guide/ocean/api.md, docs/developers_guide/ocean/index.md, docs/developers_guide/ocean/test_groups/global_convergence.md, docs/developers_guide/ocean/test_groups/index.md, docs/index.md, docs/users_guide/machines/anvil.md, docs/users_guide/machines/chicoma.md, docs/users_guide/machines/chrysalis.md, docs/users_guide/machines/compy.md, docs/users_guide/machines/cori.md, docs/users_guide/machines/index.md, docs/users_guide/machines/perlmutter.md, polaris/__init__.py
This merge adds more documentation, including:
* pages on supported and unknown machines in both guides
* Auto-generated API for the framework
Checklist
=> Add more documentation

.gitmodules, docs/developers_guide/command_line.md, docs/developers_guide/ocean/index.md, docs/developers_guide/quick_start.md, docs/users_guide/quick_start.md
The `E3SM-Project` and `MALI-Dev` submodules point to the same commits as the corresponding submodules in compass currently have.
Checklist
=> Add MPAS-Ocean, OMEGA and MALI submodules

utils/bisect/README.md, utils/bisect/bisect.py, utils/bisect/bisect_step.py, utils/bisect/example.cfg, utils/e3sm_update/README.md, utils/e3sm_update/example.cfg, utils/e3sm_update/test_e3sm_changes.py, utils/matrix/README.md, utils/matrix/example.cfg, utils/matrix/setup_matrix.py, utils/matrix/shared.py
There isn't currently a great way to test these so I'll leave that for future work.
=> Add utilities from compass

polaris/job/__init__.py, polaris/model_step.py, polaris/ocean/tests/global_convergence/__init__.py, polaris/ocean/tests/global_convergence/cosine_bell/__init__.py, polaris/ocean/tests/global_convergence/cosine_bell/forward.py, polaris/ocean/vertical/__init__.py, polaris/suite.py
This merge includes:
* a few changes of "MPAS core" --> "component" that were missed
* Moves a public method before a private one
* Get a config option as a float instead of an int for better generalization
Checklist
=> General clean-up PR

docs/developers_guide/ocean/api.md, docs/developers_guide/ocean/framework.md, docs/developers_guide/ocean/index.md, docs/users_guide/quick_start.md, polaris/model_step.py, polaris/ocean/model/ocean_model_step.py, polaris/ocean/mpas_ocean.cfg, polaris/ocean/ocean.cfg, polaris/ocean/tests/global_convergence/cosine_bell/__init__.py, polaris/ocean/tests/global_convergence/cosine_bell/forward.py, polaris/ocean/tests/global_convergence/cosine_bell/init.py
=> Ocean resources from config options

polaris/setup.py
It is often convenient to run steps on their own, so it will be convenient to have a job script (and a link to the load script) for each step.
This is the polaris port of https://github.com/MPAS-Dev/compass/pull/603
Checklist
=> Add job script to steps

polaris/step.py
The code for changing permissions was being given an incorrect directory and then was failing silently.  This merge fixes the path and also removes the silent failure (an error will be raised if the status of the download directory cannot be determined).
This merge also adds the database root and the root for each affected core to the list of directories to chmod/chown anytime any files get downloaded.
A port of https://github.com/MPAS-Dev/compass/pull/609
Checklist
=> Fix bug in changing permissions on downloaded files

docs/index.md, docs/tutorials/dev_add_test_group.md
=> Add a tutorial for adding a new test group

polaris/ocean/suites/pr.txt
The resolution didn't get updated along with the change in the test case.
Checklist
=> Fix single_column test in pr suite

docs/developers_guide/ocean/test_groups/baroclinic_channel.md, docs/developers_guide/quick_start.md, docs/tutorials/dev_add_test_group.md
=> Fixup quick-start and tutorial

docs/tutorials/dev_add_test_group.md
=> Fixup tutorial

polaris/step.py
This allows input files to be placed in a subdirectory of a step.
Checklist
closes #58
=> Make subdirectories for symlinks for input files

MANIFEST.in
This file is needed so data files (non-python files) are included in the python package.
Checklist
=> Add a `MANIFEST.in`

deploy/bootstrap.py, polaris/cache.py, polaris/io.py, polaris/viz/globe.py
There were some older style formatting strings hanging around, and I've now updated them to be f strings.
Checklist
=> Clean up outdated format strings

docs/developers_guide/quick_start.md
This is a port of https://github.com/MPAS-Dev/compass/pull/574 to polaris.
Checklist
=> Update guidance on switching between branches

docs/users_guide/ocean/test_groups/global_convergence.md, polaris/ocean/tests/global_convergence/cosine_bell/cosine_bell.cfg, polaris/ocean/tests/global_convergence/cosine_bell/forward.py, polaris/ocean/tests/global_convergence/cosine_bell/forward.yaml
=> Change cosine bell to be single layer

polaris/run/serial.py
The log filename was getting set to `None` when there is already a log file, whereas we want it to contain the name of that existing log file.
Checklist
=> Fix log filename for steps

polaris/ocean/tests/baroclinic_channel/forward.yaml
This is following up on changes from
https://github.com/E3SM-Project/E3SM/pull/5595
Checklist
=> Rename namelist implicit bottom drag namelist option

docs/users_guide/ocean/test_groups/baroclinic_channel.md
=> Fix equations in baroclinic channel User's Guide

docs/conf.py, docs/developers_guide/ocean/api.md
=> A few fixes to the docs

polaris/run/serial.py
If baseline comparison fails, raise an error at the task level not at the step level so task execution can complete.
Checklist
=> Raise error only at task level on baseline failure

docs/developers_guide/deploying_spack.md, docs/developers_guide/ocean/api.md, docs/developers_guide/ocean/tasks/geostrophic.md, docs/users_guide/quick_start.md
=> Fixes to `polaris suite` and `geostrophic` docs

deploy/spack/morpheus_gnu_openmpi.yaml
=> Update morpheus spack build

deploy/default.cfg
=> Update scorpio to v1.4.2

deploy/albany_supported.txt, deploy/petsc_supported.txt, docs/developers_guide/machines/frontier.md, docs/developers_guide/machines/index.md, docs/users_guide/machines/anvil.md, docs/users_guide/machines/chicoma.md, docs/users_guide/machines/chrysalis.md, docs/users_guide/machines/compy.md, docs/users_guide/machines/frontier.md, docs/users_guide/machines/index.md, docs/users_guide/machines/perlmutter.md, polaris/machines/frontier.cfg
=> Add Frontier as a supported machine

deploy/unsupported.txt, docs/developers_guide/machines/anvil.md, docs/developers_guide/machines/index.md, utils/matrix/setup_matrix.py
This combination cannot build MOAB.
=> Remove `gnu` with `mvapich` on Anvil

deploy/bootstrap.py
This should be fixed for all machines be included but is causing particular trouble on Compy
Checklist
=> Add `libnetcdf` to jigsaw build deps

deploy/bootstrap.py
=> Fix `conda install` before Jigsaw build

polaris/viz/planar.py
Fixes https://github.com/E3SM-Project/polaris/issues/149
Checklist
=> Fix visualization of edge quantities with periodic boundaries

utils/omega/ctest/build_and_ctest.template, utils/omega/ctest/omega_ctest.py
=> Fix omega ctest mesh

deploy/conda-dev-spec.template, deploy/default.cfg, polaris/version.py, setup.cfg
This merge includes updates to `numpy`, `matplotlib` and `mpas_tools` as well as the `E3SM-Project` submodule.
Checklist
=> Update to v0.3.0-alpha.2

polaris/ocean/tasks/isomip_plus/__init__.py, polaris/ocean/tasks/isomip_plus/mesh/planar.py
This allows us to perform conservative remapping and smoothing of topography before culling the mesh.
Checklist
=> Cull ISOMIP+ planar base mesh

docs/developers_guide/api.md, polaris/job/__init__.py, polaris/job/job_script.template, polaris/machines/frontier.cfg, polaris/machines/pm-gpu.cfg, polaris/parallel.py, utils/omega/ctest/job_script.template, utils/omega/ctest/omega_ctest.py
=> Add gpus-per-node to job scripts and resources

deploy/bootstrap.py, deploy/shared.py
In this pull request I cleaned up the file `deploy/bootstrap.py` to make the code more readable and safer.
Checklist
=> Bootstrap cleanup

.github/dependabot.yml
Just adding myself as a dependabot reviewer, alongside @xylar .
=> Add Althea as additional dependabot reviewer

.github/workflows/pre_commit_update_workflow.yml
This workflow runs weekly on Wednesday to check for updates to `pre-commit` and its dependencies. If available, the updates will be automatically applied and put into a new PR.
Checklist
=> Add `pre-commit` autoupdate workflow

docs/developers_guide/machines/index.md, docs/developers_guide/quick_start.md, polaris/machines/frontier.cfg
=> Add support for amdclang and amdclanggpu on Frontier

polaris/ocean/tasks/baroclinic_channel/rpe/__init__.py
This fixes the first failure noted in https://github.com/E3SM-Project/polaris/pull/256#issuecomment-2611284117
Checklist
=> Fix graph file symlink in baroclinic channel RPE test

polaris/ocean/suites/omega_pr.txt
Update test case names in omega pr suite
=> Update omega pr suite

pyproject.toml
In this PR, I've separated the optional and required dependencies into different categories to exclude developer tools from the required dependencies. 
Checklist
=> Separate dependencies in `pyproject.toml`

docs/developers_guide/ocean/tasks/ice_shelf_2d.md, docs/tutorials/dev_add_test_group.md, docs/users_guide/ocean/framework/vertical.md, docs/users_guide/ocean/suites.md, polaris/ocean/suites/framework_pr.txt
This suite is the `pr` suite plus some visualization and remapping tests.
Checklist
=> Add a new suite for testing the framework

docs/shared/version-switcher.js
Some fixes accidentally didn't get propagated to other repos
=> Update code for version switcher to match pyremap

polaris/tasks/ocean/external_gravity_wave/__init__.py
This path presumably changed between the beginning of development and merging.
Checklist
=> Fix incorrect import in external gravity wave

polaris/setup.py
These were missed as part of updating the syntax to work with the Omega CTest utility in #318 
Checklist
=> Fix calls to write_job_script()
