- deploy/bootstrap.py
- deploy/default.cfg
- polaris/machines/anvil.cfg
- polaris/machines/chicoma-cpu.cfg
- polaris/machines/chrysalis.cfg
- polaris/machines/compy.cfg
- polaris/machines/conda-linux.cfg
- polaris/machines/conda-osx.cfg
- polaris/machines/cori-haswell.cfg
- polaris/machines/default.cfg
- polaris/machines/pm-cpu.cfg
Fix netcdf-fortran version to match conda-forge pin
Fix how machine configs from mache and polaris are read during bootstrapping.
Checklist
> Add config files for supported machines

- .github/workflows/docs_workflow.yml
This merge changes the GitHub Action for building and pushing the docs to only copy release tags if they aren't already on the web page.  This way, we can retroactively modify old releases if we need to without them getting clobbered.
> Fix copying docs

- .github/workflows/build_workflow.yml
- deploy/conda-dev-spec.template
- deploy/default.cfg
- polaris/cache.py
- polaris/component.py
- polaris/io.py
- polaris/job/__init__.py
- polaris/list.py
- polaris/namelist.py
- polaris/ocean/vertical/grid_1d.py
- polaris/step.py
- polaris/streams.py
- polaris/suite.py
- polaris/version.py
- setup.cfg
To save a little trouble, an import shortcut has been added to polaris.io for `imp_res` that handles both different imports for python <=3.8 and the complaints that mypy has about these imports.
This merge also includes an update to `mache 1.13.0` and to `polaris 0.1.0-alpha.2`.
Checklist
> Fix deprecated calls to `importlib.resources`

- docs/developers_guide/ocean/index.md
- docs/developers_guide/ocean/models/index.md
- docs/developers_guide/ocean/models/mpas_ocean.md
- docs/users_guide/ocean/index.md
Add some description of the supported ocean models (now just MPAS-Ocean) to documentation. The focus here is configuration options that are most relevant to developing test cases.
Checklist
> Add ocean model descriptions to docs

- docs/developers_guide/organization.md
Add test suite descriptions to the documentation. This is intended to provide developers with a sense for how to design their tests for a particular suite and which suite to add test cases to.
Checklist
> Add test suite guidance to documentation

- docs/developers_guide/machines/index.md
- docs/developers_guide/quick_start.md
> Fix name of configure_polaris_envs.py in docs

- docs/developers_guide/api.md
- docs/developers_guide/framework.md
- polaris/ocean/tests/baroclinic_channel/default/__init__.py
- polaris/ocean/tests/baroclinic_channel/initial_state.py
- polaris/ocean/tests/baroclinic_channel/viz.py
- polaris/viz/__init__.py
- polaris/viz/polaris.mplstyle
This PR ports the `plot_horiz_field` function from `compass/ocean/tests/isomip_plus/viz/__init__.py` into a shared viz folder. There are relatively minor changes related to this being used outside `plot_horiz_series` and making the figure size match the domain aspect ratio. To demonstrate its functionality, it is added to the `initial_state` step of the `baroclinic_channel` test case.
Two functions are also needed:
* `_remove_boundary_edges_from_mask` makes sure that the periodic edges are not included (those polygons would span from one edge of the periodic domain to the other and obscure the other polygons)
* `_compute_cell_patches` is a direct port from `compass/ocean/tests/isomip_plus/viz/__init__.py`
* `_compute_edge_patches` is a new function analogous to `_compute_cell_patches` …
> Add planar horizontal viz

- docs/developers_guide/api.md
- docs/developers_guide/organization/steps.md
- polaris/run/serial.py
- polaris/setup.py
- polaris/step.py
A step can now have a list of other steps that it depends on.  This is useful when file-base dependencies cannot be used (e.g. the file names cannot be known at setup time).
This merge adds a dictionary of dependencies to each step (empty by default) and a method, `add_dependency()` for adding another step as a dependency.
As fleshed out in the documentation, the dependency *must* run before the dependent step.  The results of running the dependency are pickled at the end of the run (each dependency is identified by its `is_dependency` attribute being `True`), and then unpickled along with the dependent step before the dependent step runs.  This allows the dependent step to access all attributes of the dependency, including any changes during the dependency's run.
We check to make sure …
> Add dependencies to Step class

- docs/users_guide/ocean/test_groups/baroclinic_channel.md
- polaris/ocean/tests/baroclinic_channel/baroclinic_channel.cfg
- polaris/ocean/tests/baroclinic_channel/baroclinic_channel_test_case.py
This is a port of https://github.com/MPAS-Dev/compass/pull/605
The following description is copied from there.
This PR adjusts the number of cells used in meshes for the baroclinic channel test case to ensure the 'standard' 160x500km domain is defined. Previously, the channel has had a shorter y-length of sqrt(3)/2 * 500 => 433km.
- When using the `make_planar_hex_mesh` routine, the number of cells along the y-axis should be scaled by `2/sqrt(3)` to account for hexagonal geometry.
The channel is a standard community test case, and use of the 160x500km domain enables model intercomparison, e.g.:
- Ilıcak, M., Adcroft, A.J., Griffies, S.M. and Hallberg, R.W., 2012. Spurious dianeutral mixing and the role of momentum closure. Ocean Modelling, 45, pp.37-58.
- Petersen, M.R., Jacobsen, D.W., …
> Adjust ny for baroclinic channel to give 500 km domain

- docs/developers_guide/framework/remapping.md
- docs/developers_guide/framework/visualization.md
- docs/developers_guide/organization/components.md
- docs/developers_guide/organization/steps.md
- docs/developers_guide/organization/test_cases.md
- docs/developers_guide/organization/test_groups.md
- polaris/components.py
- polaris/mesh/spherical.py
- polaris/ocean/__init__.py
- polaris/ocean/tests/baroclinic_channel/__init__.py
- polaris/ocean/tests/baroclinic_channel/baroclinic_channel_test_case.py
- polaris/ocean/tests/baroclinic_channel/initial_state.py
- polaris/ocean/tests/baroclinic_channel/rpe_test/analysis.py
- polaris/ocean/tests/baroclinic_channel/viz.py
- polaris/ocean/tests/global_convergence/__init__.py
- polaris/ocean/tests/global_convergence/cosine_bell/__init__.py
- polaris/ocean/tests/global_convergence/cosine_bell/analysis.py
- polaris/ocean/tests/global_convergence/cosine_bell/init.py
- polaris/ocean/tests/global_convergence/cosine_bell/viz.py
- polaris/remap/mapping_file_step.py
- polaris/setup.py
This is more consistent with the API documentation, which uses the shorter names, and also what we want folks to use in new test groups they make.
Checklist
> Use shorter imports for Component, TestGroup, etc.

- .github/workflows/build_workflow.yml
The GitHub Action build workflow works fine on PRs but was having trouble once the PR gets merged because now the branch `main` already exists (and the workflow tries to create it).  This merge will hopefully fix that issue.
> Fix error when building docs on main after merge

- docs/developers_guide/api.md
- docs/developers_guide/framework/mesh.md
- docs/developers_guide/ocean/api.md
- docs/users_guide/ocean/test_groups/baroclinic_channel.md
- polaris/mesh/planar.py
- polaris/ocean/config/output.yaml
- polaris/ocean/tests/baroclinic_channel/baroclinic_channel.cfg
- polaris/ocean/tests/baroclinic_channel/baroclinic_channel_test_case.py
- polaris/ocean/tests/baroclinic_channel/forward.py
- polaris/ocean/tests/baroclinic_channel/initial_state.py
- polaris/ocean/tests/baroclinic_channel/rpe_test/__init__.py
- polaris/ocean/tests/baroclinic_channel/rpe_test/analysis.py
- polaris/ocean/tests/baroclinic_channel/viz.py
This merge includes some clean-up to the baroclinic channel test group that I feel is important based on writing the tutorial.
First, this merge adds a framework-level function that computes `nx` and `ny` for a uniform, hexagonal planar mesh.  The function takes into account the staggered nature of the hexagons in the y direction as corrected in #37.
Then, in the baroclinic channel, instead of computing these properties in the test case and storing them in config options, they are computed using a framework-level function at setup in forward (to get the cell count) and then again at runtime in `initial_state` to make the mesh.  Initial state stores `nx` and `ny` as attributes in the initial state output file.  The RPE analysis step then reads the attributes from the initial state file …
> Clean up baroclinic channel

- docs/developers_guide/docs.md
- docs/users_guide/ocean/test_groups/baroclinic_channel.md
- docs/users_guide/ocean/test_groups/global_convergence.md
- docs/users_guide/ocean/test_groups/template.md
This PR adds a template for test groups for the User's Guide to help ensure all the details relevant to the configuration of a test case in a test group are provided. 
Checklist
> Add User's Guide template for test groups

- polaris/parallel.py
We want to explicitly specify how many nodes to use in `srun` calls for slurm steps because otherwise we may end up with a job running on more nodes than needed and an incompatible PIO task count.
Checklist
> Explicitly specify nodes in srun calls

- polaris/step.py
When you add an input in a subdirectory and the target is also in the subdirectory of another step, polaris was previously incorrectly creating an absolute path to the input relative to the step's workdir, rather than the subdirectory where the symlink exists.  This merge fixes that bug.
Checklist
closes #61
> Fix check for inputs in subdirectories

- docs/developers_guide/api.md
- docs/developers_guide/framework/remapping.md
- polaris/ocean/tests/global_convergence/cosine_bell/viz.py
- polaris/remap/mapping_file_step.py
Rather than using `pyremap` to do a `subprocess` call, we construct a list of command-line arguments and let polaris take care of the MPI arguments.
Checklist
> Switch `MappingFileStep` to be a command-line step

- docs/developers_guide/command_line.md
- polaris/run/serial.py
I renamed these to `steps_to_skip` and `--skip-steps` because it was more understandable, the former was a little confusing to read.
Checklist
> Rename `steps_not_to_run` and `--no-steps`

- polaris/ocean/model/ocean_model_step.py
This seems to work better on Perlumtter.
Also, fix rounding (remove incorrect factor of 0.5)
Checklist
> Make ocean ntasks and min_tasks a multiple of 4

- docs/tutorials/dev_add_test_group.md
- polaris/logging.py
- polaris/run/serial.py
- polaris/step.py
This PR changes a few things concerning loggers. Some loggers in `run/serial.py` have been renamed for better code readability, indicating when they are logging to stdout vs an internal file. The `log_filename` attribute in `Step` has been explicitly set to None by default, as opposed to an empty string. And in general, some "compass" wording needed to be changed to "polaris".
Checklist
> Logger cleanup and clarification

- polaris/default.cfg
- polaris/parallel.py
- polaris/run/serial.py
- polaris/step.py
This is a port from changes made in Compass:
https://github.com/MPAS-Dev/compass/pull/538
This merge changes `run.serial` and `parallel` so we only poll for slrum resources once and use that information for all test cases and steps.
This merge also removes the error message when you run on a login node.  Instead, a login node is allocated a small number of cores (4 by default) and isn't allowed to run MPI jobs (it only supports one task).
To accommodate this, the `Step.constrain_resources()` method takes a dictionary of available resources instead of just the number of available cores.
Checklist
> Check available parallel resources only once

- docs/developers_guide/api.md
- polaris/parallel.py
Creating the command is now a process that can be called without running the command, for use when we wish to run the command elsewhere.
Checklist
> Separate creating parallel command and running command

- docs/developers_guide/organization/steps.md
- polaris/step.py
This is a port from changes made in Compass:
https://github.com/MPAS-Dev/compass/pull/573
Previously, nothing was preventing `cpus_per_task` from being more than the number of cores on a node. This is inconvenient because unsafe or non-performant behavior will occur if more python threads are used than cores on a node.
This merge changes the way resources are constrained. First, `cpus_per_task` is constrained to be less than the lower of the number of cpus on a node or the number of total cores available. Then, we check to see if `cpus_per_task` is smaller than the minimum allowed for the given step. Next, we allow all tasks to have the same `cpus_per_task` and constrain the number of tasks not to exceed the total available resources. Finally, we check to make sure the number of tasks is …
> Change algorithm for constraining resources

- docs/developers_guide/framework/remapping.md
- docs/developers_guide/ocean/test_groups/global_convergence.md
- docs/users_guide/ocean/test_groups/global_convergence.md
- polaris/ocean/tests/global_convergence/__init__.py
- polaris/ocean/tests/global_convergence/cosine_bell/__init__.py
- polaris/ocean/tests/global_convergence/cosine_bell/viz.py
- polaris/remap/mapping_file_step.py
- polaris/viz/globe.py
This merge also modifies the visualization so the central longitude is 180 degrees, not 0, so the cosine bell shape is in the center of the domain.
To accommodate this change, the remapping and global plotting has also been modified to support an arbitrary lower bound in longitude (in this case 0 degrees) rather than always using -180.  Manually placing grid lines on plots did not seem to work with these changes but automatic grid line locations seem to be fine so this merge removes manual grid line locations.
Checklist
> Make versions of cosine bell with and without viz steps

- polaris/run/serial.py
- polaris/step.py
Make pickle file of a dependency an input of the dependent step. In order for a bash app to be a dependency of another bash app, we need to use a data future, so we use the output pickle file as an input.
Checklist
> Make pickle file of dependency an input

- docs/developers_guide/api.md
- polaris/parallel.py
This function was meant to be removed in a prior pull request (https://github.com/E3SM-Project/polaris/pull/76), but was missed when rebasing from Compass.
Checklist
> Remove unused `check_parallel_system` function

- docs/developers_guide/api.md
- polaris/job/__init__.py
I made this change so that we can access the Slurm options without actually writing a job script, which may be useful for task parallelism.
Checklist
> Get Slurm options in a separate function

- docs/developers_guide/api.md
- polaris/run/__init__.py
- polaris/run/serial.py
There is a little bit of setup that is common to setting up a suite, test case, or step, and we can modularize it better. This will be further utilized during development of the parallel counterpart to `run.serial`.
Checklist
> Pull out common setup between run procedures

- polaris/run/serial.py
If a step fails, we want to remove its `step_after_run.pickle` file to indicate its failure. However, the file might be nonexistent, so in that case we should just go on to report the error and skip the removal.
Checklist
closes #85
> Ignore nonexistent `step_after_run.pickle` file

- docs/developers_guide/ocean/api.md
- docs/developers_guide/ocean/test_groups/index.md
- docs/developers_guide/ocean/test_groups/manufactured_solution.md
- docs/users_guide/ocean/test_groups/index.md
- docs/users_guide/ocean/test_groups/manufactured_solution.md
- polaris/ocean/__init__.py
- polaris/ocean/suites/nightly.txt
- polaris/ocean/suites/pr.txt
- polaris/ocean/tests/manufactured_solution/__init__.py
- polaris/ocean/tests/manufactured_solution/analysis.py
- polaris/ocean/tests/manufactured_solution/convergence/__init__.py
- polaris/ocean/tests/manufactured_solution/exact_solution.py
- polaris/ocean/tests/manufactured_solution/forward.py
- polaris/ocean/tests/manufactured_solution/forward.yaml
- polaris/ocean/tests/manufactured_solution/initial_state.py
- polaris/ocean/tests/manufactured_solution/manufactured_solution.cfg
- polaris/ocean/tests/manufactured_solution/viz.py
- polaris/viz/__init__.py
- polaris/viz/polaris.mplstyle
This PR adds the manufactured solution test group and the convergence test case as described in [Bishnu et al.(2023)](https://doi.org/10.22541/essoar.167100170.03833124/v1). The test case depends on https://github.com/E3SM-Project/E3SM/pull/5725. The test currently "fails" with a convergence rate of 0.9 rather than ~2 due to https://github.com/E3SM-Project/E3SM/issues/5364.
Checklist
> Add manufactured solution test group

- polaris/ocean/suites/nightly.txt
- polaris/ocean/suites/pr.txt
I think we want to remove this test from our suites for now since it is failing "on purpose" (i.e. we know the MPAS-Ocean code needs to be fixed to allows the solution to converge at the desired rate) but this is confusing for those who are trying to use these suites to validate unrelated code.
Checklist
closes #89
> Remove `manufactured_soluiton` test case from suites

- deploy/shared.py
- polaris/cache.py
- polaris/list.py
- polaris/run/serial.py
- polaris/setup.py
- polaris/suite.py
- utils/bisect/bisect.py
- utils/bisect/bisect_step.py
- utils/e3sm_update/test_e3sm_changes.py
- utils/matrix/setup_matrix.py
While testing, I noticed that some of these descriptions had typos that made them hard to read. I went ahead and looked through other argument parsing help messages to fix some typos and generally make the formatting consistent (such as adding or removing periods).
Checklist
> Reformat command line help descriptions

- polaris/step.py
This fixes a bug that occurs in the process of giving a step its input files. The inputs list is never actually updated with the filenames of the input files, which would cause missing files to go unnoticed.
Checklist
closes https://github.com/E3SM-Project/polaris/issues/91
> Update step inputs attribute with input filenames

- polaris/ocean/tests/global_convergence/cosine_bell/forward.py
This PR allows users to change the number of vertical levels in either the cfg file in the repo or the cfg file in a test case that is already set up.
Checklist
> Fixup cosine bell test: Allow user changes to vert_levels cfg option

- .pre-commit-config.yaml
- deploy/conda-dev-spec.template
- docs/developers_guide/quick_start.md
Flynt is a package that automatically converts older-style formatting strings to f-strings. I've added this to pre-commit so that any incoming changes will use f-strings by default.
Checklist
> Add flynt package to linter for updating format strings

- polaris/ocean/tests/baroclinic_channel/init.py
- polaris/ocean/tests/baroclinic_channel/rpe/analysis.py
- polaris/ocean/tests/baroclinic_channel/viz.py
- polaris/ocean/tests/global_convergence/cosine_bell/analysis.py
- polaris/ocean/tests/global_convergence/cosine_bell/init.py
- polaris/ocean/tests/global_convergence/cosine_bell/viz.py
- polaris/ocean/tests/inertial_gravity_wave/init.py
- polaris/ocean/tests/inertial_gravity_wave/viz.py
- polaris/ocean/tests/manufactured_solution/init.py
- polaris/ocean/tests/manufactured_solution/viz.py
- polaris/ocean/tests/single_column/init.py
For OMEGA, mesh variables will be located in a separate netcdf file from the output. This PR always loads mesh variables from the mesh netcdf (usually `mesh.nc` or `culled_mesh.nc`). Some of my changes from the init netcdf to the mesh netcdf file are unnecessary but I think it improves code clarity. 
Checklist
> Assume mesh variables only in mesh file

- polaris/ocean/tests/baroclinic_channel/restart/__init__.py
Because we don't know the filename of the restart file at setup time, we need to instead make the `full_run` step an explicit dependency of the `restart_run` step.
Checklist
> Add dependency in restart test case

- deploy/conda-dev-spec.template
- polaris/ocean/tests/global_convergence/cosine_bell/viz.py
- setup.cfg
The `lon` and `lat` fields are not available in the MPAS mesh file, but rather come from remapping to a regular lat-lon grid.
We also need to skip `matplotlib` version 3.7.2 because of a known bug: https://github.com/matplotlib/matplotlib/pull/26291
Checklist
> Fix cosine bell viz step

- polaris/ocean/tests/baroclinic_channel/rpe/__init__.py
Without this, each step is listed twice in steps_to_run after setup.
Checklist
> Remove steps from `steps_to_run` in `baroclinic_channel` RPE

- deploy/albany_supported.txt
- deploy/bootstrap.py
- deploy/conda-dev-spec.template
- deploy/default.cfg
- deploy/petsc_supported.txt
- deploy/shared.py
- deploy/spack/morpheus_gnu_openmpi.yaml
- deploy/unsupported.txt
- docs/developers_guide/deploying_spack.md
- docs/developers_guide/machines/index.md
- docs/index.md
- polaris/machines/__init__.py
- polaris/machines/morpheus.cfg
- polaris/setup.py
- polaris/version.py
This merge brings over many of the changes from the compass PR https://github.com/MPAS-Dev/compass/pull/641.  This includes:
* Bringing in a new `mache` with support for Intel on Perlmutter (not yet supported in polaris) and which allows for spack environment builds on non-E3SM machines
* Updates to a new `pyremap` that supports specifying the NetCDF format and (where appropriate) the xarray NetCDF engine
* Names spack clones the same as the spack environment that will be created in them (to avoid multiple developers trying to use the same clone of spack)
* Adds support for deploying on supported machines that aren't part of `mache` (non-E3SM machines), including documentation and an example (my linux laptop)
* Update versions of HDF5, NetCDF-C, NetCDF-Fortran, Parallel-NetCDF, ESMF and …
> Update to v0.2.0

- docs/developers_guide/api.md
- polaris/run/__init__.py
- polaris/run/serial.py
This PR pulls out some common code that will be used between `run.serial` and `run.parallel`. I also took the chance to do a bit of cleanup and renaming for general clarity in `run.serial`. 
Checklist
> Modularization and cleanup

- polaris/ocean/tests/inertial_gravity_wave/init.py
The output files for the init step aren't being added to the step's outputs attribute, which is causing issues when running in task parallel.
Checklist
> Fix dependencies in inertial gravity wave convergence test

- polaris/run/serial.py
This merge adds timers to steps as they run.  This is sometimes convenient for long-running steps.
It also adds a display for the duration of the test case, step or suite in hours (important for long tests).
Checklist
> Add timers to steps as they run in a suite or task

- deploy/default.cfg
- polaris/mesh/spherical.py
- polaris/viz/__init__.py
The newer MPAS-Tools brings in the new, faster version of the MPAS mesh converter and cell culler, as well as tools for sorting mesh indices for improved MPAS-Ocean parallel and memory performance.
This merge also ports over a small change from https://github.com/MPAS-Dev/compass/pull/659 to better support large spherical meshes.
Checklist
> Update to `mpas_tools` v0.23.0

- polaris/task.py
The check needs to be on the name of the step, not the subdirectory.
> Fix detecting step already added to task

- polaris/ocean/rpe.py
- polaris/ocean/tasks/baroclinic_channel/baroclinic_channel.cfg
- polaris/ocean/tasks/baroclinic_channel/forward.py
- polaris/ocean/tasks/baroclinic_channel/rpe/__init__.py
- polaris/ocean/tasks/baroclinic_channel/rpe/analysis.py
- polaris/ocean/tasks/cosine_bell/__init__.py
- polaris/ocean/tasks/cosine_bell/analysis.py
Rather than using some iffy custom plotting techniques, this uses the framework `plot_horiz_field()` function.
This merge also fix a bug in the placement of `nu` being added to model config options.  Before this fix, the `forward.yaml` options were overwriting the `nu` value so all RPE runs used the same viscosity.  This problem was introduced in the initial port of baroclinic channel (https://github.com/E3SM-Project/polaris/commit/875e7fe6b6e3a34939adeacb4594ab9e07ec5f17) but apparently after initial testing showed that it worked as expected.
Checklist
> Clean up RPE analysis step and framework

- deploy/conda-dev-spec.template
- polaris/remap/mapping_file_step.py
We need to make a few changes to remapping to take advantage of pyremap 1.1.0 and later.  This merge switches to only using SCRIP, not ESMF, format in anticipation of adding `mbtempest` support.  It uses the new mesh descriptors for cell and vertex meshes.
Some bugs in projection and point descriptor support have also been fixed.
Checklist
> Updates for pyremap >= 1.1.0

- docs/developers_guide/framework/config.md
- docs/developers_guide/ocean/api.md
- docs/developers_guide/ocean/framework.md
- docs/developers_guide/ocean/tasks/cosine_bell.md
- docs/developers_guide/organization/tasks.md
- docs/users_guide/ocean/tasks/cosine_bell.md
- polaris/ocean/convergence/spherical/__init__.py
- polaris/ocean/convergence/spherical/forward.py
- polaris/ocean/convergence/spherical/spherical.cfg
- polaris/ocean/model/__init__.py
- polaris/ocean/model/time.py
- polaris/ocean/tasks/cosine_bell/__init__.py
- polaris/ocean/tasks/cosine_bell/analysis.py
- polaris/ocean/tasks/cosine_bell/cosine_bell.cfg
- polaris/ocean/tasks/cosine_bell/forward.py
- polaris/ocean/tasks/cosine_bell/forward.yaml
- polaris/ocean/tasks/cosine_bell/init.py
- polaris/ocean/tasks/cosine_bell/viz.py
- polaris/setup.py
This merge adds some shared framework for spherical convergence tests with constant resolution meshes like `cosine_bell` and soon `geostrophic` and the various `sphere_transport` tests.
A new `SphericalConvergenceForward` parent class does most of the work involved in forward runs for convergence tests, including determining the approximate number of cells in the mesh (for constraining required resources), computing a time step based on the mesh resolution, and setting the run duration and output interval based on a config option.
A set of common (standardized) config options in the `spherical_convergence` section helps support this approach.
The cosine bell tests have been updated to use the shared framework, and the documentation as also been updated.
We no longer automatically add a …
> Add shared ocean framework for spherical convergence tests

- docs/developers_guide/api.md
- docs/developers_guide/framework/index.md
- docs/developers_guide/framework/mpas.md
- docs/developers_guide/ocean/api.md
- docs/developers_guide/ocean/framework.md
- polaris/mpas/__init__.py
- polaris/mpas/area.py
- polaris/mpas/time.py
- polaris/ocean/convergence/spherical/analysis.py
This merge adds a `polaris.mpas` module that has:
* an `area` module that currently has a function `area_for_field()` for computing the area associated with a given data array from and MPAS output file.  This is useful for getting different areas for fields on cells, edges and vertices.
* a `time` module where I have moved `time_index_from_xtime()`.  I also added an optional `start_xtime` argument in case the start time isn't written to the output file.
`SphericalConvergenceAnalysis` has been updated to use these.
This merge also adds a `get_output_field()` method to `SphericalConvergenceAnalysis` that can be overridden to compute fields based on MPAS output. This is useful, for example, in #120, where I need to compute the water column thickness (not an output variable from MPAS-Ocean) …
> Clean up and add method to spherical convergence analysis

- polaris/run/serial.py
Before this merge, we were incorrectly printing a message that baselines passed when no baseline comparison was made.  With this fix, a message about baselines is only printed if baseline comparisons were performed.
Checklist
closes #132
> Only print task baseline status if basline compared

- polaris/config.py
We don't want to do this for config options that start with other config options.
Checklist
> Fix conversion to absolute paths in config files

- polaris/run/__init__.py
- polaris/run/serial.py
Before this merge, we were not setting a config's `filepath` attribute after loading the config options from a file.  This causes the step to fail for cryptic reasons if it is rerun later as part of a test suite (because it failed the first time).
Checklist
> Set config.filepath after loading new config options

- docs/users_guide/ocean/tasks/geostrophic.md
- polaris/ocean/tasks/geostrophic/analysis.py
- polaris/ocean/tasks/geostrophic/geostrophic.cfg
We want to have a higher threshold on velocity convergence since it is better behaved than water-column thickness.
Checklist
> Use Separate geostrophic thresholds for h and norm. vel.

- .github/workflows/build_workflow.yml
- deploy/conda-dev-spec.template
- polaris/cache.py
- polaris/component.py
- polaris/io.py
- polaris/job/__init__.py
- polaris/list.py
- polaris/machines/__init__.py
- polaris/namelist.py
- polaris/ocean/vertical/grid_1d.py
- polaris/seaice/tasks/single_column/standard_physics/viz.py
- polaris/step.py
- polaris/streams.py
- polaris/suite.py
- polaris/viz/style.py
- polaris/yaml.py
- setup.cfg
This merge drop support for python 3.8 in deployment and CI, since it is nearing end of life and is giving us a headache.
This allows us to drop a bunch of `importlib.resources` special cases that were for handling python 3.8.
Checklist
> Drop python 3.8

- docs/developers_guide/api.md
- polaris/ocean/tasks/manufactured_solution/viz.py
- polaris/viz/planar.py
This merge includes a few pieces of clean-up for `plot_horiz_field()` that came up while porting the ISOMIP+ initial condition.
Checklist
> Clean up `plot_horiz_field()`

- polaris/setup.py
This merge changes the `-t` or `--tasks` flag to `polaris setup` to allow multiple task to be specified.
Since there is not a sensible way to specify cached steps for each of several tasks, the `--cached` flag only works when a single task is specified to to `-t` or `-n`.
Checklist
> Allow multiple tasks to be set up with `-t` flag

- docs/developers_guide/framework/visualization.md
- polaris/ocean/tasks/baroclinic_channel/init.py
- polaris/ocean/tasks/baroclinic_channel/rpe/analysis.py
- polaris/ocean/tasks/baroclinic_channel/viz.py
- polaris/ocean/tasks/inertial_gravity_wave/viz.py
- polaris/ocean/tasks/manufactured_solution/viz.py
- polaris/viz/planar.py
This merge returns `patches` and `patch_mask` variables from `plot_horiz_field()` so they can be reused in subsequent calls.  This should save a lot of time in tests that plot many fields.  Corresponding input arguments have been added to take  `patches` and `patch_mask`  from previous plots on the same mesh. 
**Note:** you need need to keep patches for cells and edges separate.
This merge also removes some ocean-specific variable and dimension names.  This because the function lives in the top-level framework so it should work for any component.  Instead of providing `maxLevelCell` in `ds`, the function needs to be called with a `cell_mask` argument that should typcially be `cell_mask = ds_init.maxLevelCell >= 1` (though it could be another field such as `landIceFloatingMaks` if …
> Allow patches to be reused in `plot_horiz_field()`

- polaris/config.py
- polaris/ocean/mesh/spherical.py
- polaris/setup.py
- polaris/step.py
- polaris/task.py
This merge fixes two main issues with shared config files:
1. The main one is adding an explicit attribute of steps to indicate whether they have a shared config (the alternative being that they use the config for the task they belong to). Previously, a step was assumed to have a shared config if it belonged to multiple tasks but that causes trouble when a conceptually shared step happens to belong to only one task (e.g. because other tasks may use it in the future).
2. The minor fix is that only the tasks and steps requested during setup have their config files linked.  Previously, symlinks to the shared config were being created for all tasks and steps that used the config, even if they were not requested at setup.  This created confusing directories for unrequested tasks that just had …
> Fix issues with shared config files

- .github/workflows/build_workflow.yml
- .github/workflows/docs_workflow.yml
- configure_polaris_envs.py
- deploy/bootstrap.py
- deploy/load_polaris.template
- deploy/shared.py
- docs/developers_guide/deploying_spack.md
- docs/developers_guide/quick_start.md
- docs/tutorials/dev_add_test_group.md
- docs/users_guide/machines/index.md
- docs/users_guide/quick_start.md
- utils/e3sm_update/README.md
This is the equivalent of the Compass PR https://github.com/MPAS-Dev/compass/pull/751.
Checklist
> Remove `mamba` command and switch to Miniforge3

- deploy/bootstrap.py
- deploy/load_polaris.template
- docs/developers_guide/command_line.md
- docs/developers_guide/quick_start.md
If the load script is for a different polaris version, a developer is told to rerun the configure script.
Checklist
closes #155 
closes #154
> Add a version check to load script

- deploy/bootstrap.py
- docs/developers_guide/deploying_spack.md
- polaris/machines/anvil.cfg
- polaris/machines/chicoma-cpu.cfg
- polaris/machines/chrysalis.cfg
- polaris/machines/compy.cfg
- polaris/machines/morpheus.cfg
- polaris/machines/pm-cpu.cfg
> Split spack software and libs

- .github/workflows/build_workflow.yml
- .github/workflows/docs_workflow.yml
- .gitmodules
- configure_polaris_envs.py
- deploy/bootstrap.py
- deploy/conda-dev-spec.template
- deploy/default.cfg
- deploy/shared.py
- docs/developers_guide/quick_start.md
- docs/index.md
- setup.cfg
This is a port of https://github.com/MPAS-Dev/compass/pull/755 from Compass.
The reason for making `jigsaw-python` a submodule of Polaris is:
1. It will allow development of jigsaw and jigsaw-python alongside compass (much as we currently support development of MPAS-Ocean and MALI alongside compass).
2. It is expected to increase the visibility of jigsaw and jigsaw-python within E3SM workflows.
3. The jigsaw and jigsaw-python repos do not include release tags so a submodule is the most feasible way to get the latest versions of the software
The submodule currently points to Jigsaw-Python v1.0.0, which includes Jigsaw v1.0.0.
Checklist
> Add `jigsaw-python` as a submodule

- deploy/bootstrap.py
- deploy/default.cfg
We will add MOAB to the lib environment, rather than the one for software, because there is work underway to use MOAB within MPAS components.
Checklist
> Add MOAB to the spack build

- polaris/parallel.py
Some systems like Frontier have cores that aren't allocatable. These need to be excluded from the core count that Polaris determines from slurm.
Checklist
> Fix slurm handling of allocatable cores

- polaris/machines/frontier.cfg
Should apparently be 56 rather than 64 (though that's hard to find in the docs).
Checklist
> Fix cores_per_node for Frontier

- deploy/bootstrap.py
This merge explicitly points to the libnetcdf that should be used in the Jigsaw build.  It also breaks the jigsaw build into its own function.
Checklist
> Fix libnetcdf in jigsaw build

- polaris/parallel.py
Compy and Anvil don't think their nodes have any allocated cores (all idle) so we will use the total number of cores per node instead.
Checklist
> Fix `cores_per_node` calculation on Compy and Anvil

- utils/omega/ctest/README.md
- utils/omega/ctest/build_and_ctest.template
- utils/omega/ctest/job_script.template
- utils/omega/ctest/omega_ctest.py
The utility checks out submodules, builds Omega and runs CTests (either directly on a compute node or through a batch job on a login node).
Checklist
> Add utility for building Omega and running ctests

- utils/omega/ctest/omega_ctest.py
This merge updates the mesh used in Omega's CTests to an oQU240 initial condition taken from `inputdata` on the E3SM server. This is necessary for the `HORZMESH_TEST` to pass, since that test assumes realistic total ocean area and coriolis parameter.
This merge also updates the `Omega` submodule to the latest `develop` (hash: ca19fa9)
Checklist
> Switch the mesh used for Omega CTests 

- docs/users_guide/ocean/framework/vertical.md
- polaris/ocean/ocean.cfg
- polaris/ocean/vertical/zlevel.py
- polaris/ocean/vertical/zstar.py
For MPAS-O configurations where tracers are active, we want a minimum of 3 vertical levels. This was not easy to enforce for z-star (or z-level) coordinates. This is one possible work-around for z-star coordinates which relies on new `min_vert_levels` and `min_layer_thickness` config options AND requires that the config option `bottom_depth` be set to less than or equal to `min(bottomDepth + ssh)` (but if less than this value, it may be that `min(maxLevelCell - minLevelCell + 1) > min_vert_levels`).
Checklist
> Workaround for z-star minimum number of vertical levels

- README.md
This PR simply updates the link to the Polaris documentation in the README to the newer style of URL that's being adopted for other E3SM projects.
> Update docs link to newer URL style

- docs/developers_guide/api.md
- docs/developers_guide/framework/io.md
- polaris/io.py
- polaris/step.py
- utils/omega/ctest/omega_ctest.py
Without this, the files are being left with permissions such that only the person downloading the file can read them.
To support this, we move code for updating permissions to the shared `io` module 
Checklist
fixes #198
> Set permissions for Omega CTest downloads 

- polaris/ocean/tasks/isomip_plus/__init__.py
> Don't smooth ISOMIP+ topography on base mesh

- deploy/bootstrap.py
- deploy/conda-dev-spec.template
- docs/developers_guide/framework/remapping.md
- docs/developers_guide/quick_start.md
- docs/developers_guide/troubleshooting.md
- docs/users_guide/quick_start.md
- polaris/model_step.py
- polaris/ocean/tasks/isomip_plus/__init__.py
- polaris/remap/mapping.cfg
- polaris/remap/mapping_file_step.py
- polaris/remap/remap.cfg
- polaris/run/serial.py
- polaris/step.py
This merge adds support for creating mapping files with `mbtempest` in addition to `ESMF_RegridWeightGen`.  I have added `moab` with `tempest-remap` as a conda dependency.
Because `mbtempest` creates mapping files in 2 steps (first creating intersections and then creating the mapping file), I have modified the `args` attribute of `Step` to be a list of lists, allowing multiple commands.  Each command is required to take the same parallel resources, which is fine for `mbtempest`.
I have added a new config file `mapping.cfg` with a `[mapping]` section and a `map_tool` config option (either `esmf` or `moab`).  I have made `moab` the default.
Finally, I have updated the `isomip_plus` tests include the new mapping config.
Checklist
> Add support for creating mapping files with `mbtempest`

- deploy/bootstrap.py
- deploy/default.cfg
- polaris/machines/chicoma-cpu.cfg
- polaris/version.py
- utils/omega/ctest/omega_ctest.py
MPAS-Ocean with `pr`:
Omega CTests:
> Update to 0.4.0-alpha.1

- polaris/model_step.py
- utils/bisect/bisect_step.py
- utils/bisect/example.cfg
This merge fixes the `--copy_exectable` flag to `polaris setup`, which referred to nonexistent config options.
It also fixes the way E3SM submodules are checked out at the beginning of each bisection step.  The submodule is cleaned, hard-reset to the `HEAD` and then submodules are recursively checked out to ensure that every step is starting from a clean state.
Checklist
> Fix the `bisect` utility

- deploy/shared.py
There are two functions relating to bashrc in `deploy.shared` that are no longer used, so I removed them.
Checklist
> Remove unused `bashrc` functions

- configure_polaris_envs.py
- deploy/shared.py
- deploy/spec-bootstrap.txt
This PR includes some general cleanup that I did in `configure_polaris_envs.py` and `deploy/bootstrap.py`, as well as a slight change to the commands which install mache. The cleanup I did consisted of the following:
* Privatized all applicable methods
* Re-ordered some methods
* Narrowed the scope of some try/catch blocks (such as catching a `FileNotFound` error instead of a more general `OSError`)
* Removed some unnecessary try/catch blocks (in the case of `makedirs()` which has a built-in `FileExistsError` check)
The installation of mache now calls upon a new file, `deploy/spec-bootstrap.txt` instead of listing mache's dependencies directly in the configure script. This change is both to make the script more modular and to make updating this list easier. 
Checklist
> Cleanup `configure_polaris_envs.py` and `deploy/shared.py`

- deploy/unsupported.txt
- polaris/machines/chicoma-cpu.cfg
This merge also updates the Omega submodule to latest develop, which is needed to be able to run the CTest utility on Chicoma (because of the need to specify an account).
Checklist
> Add nvidia to chicoma-cpu

- docs/developers_guide/quick_start.md
In this PR I just added a link inside of the quick start documentation for the Omega CTest utility. I built the documentation locally and it looks correct to me.
Checklist
> Add link to Omega CTest in Quick Start

- .github/workflows/build_workflow.yml
- deploy/bootstrap.py
- deploy/default.cfg
- polaris/version.py
This merge updates versions of ESMF, ParallelIO and PNetCDF for conda environments.  These were needed for compatibility with the required version of MPAS-Tools.  (It won't affect spack deployments until we update to 1.5.0-alpha.1.)  As a result, the Polaris alpha version has been bumped to 2.
This merge also fixes a check for a software spack environment in the bootstrap stage of deployment.  The check is only performed if we are on a "known" machine.
GitHub Actions has been updated to deploy a full conda environment including compilers and MPI support.  This should catch incompatibilities like emerged between MPAS-Tools and other dependencies specified in `deploy/default.cfg`.
Checklist
fixes #213
> Fix deployment on unknown machines

- docs/developers_guide/deploying_spack.md
I noticed a few typos on the [Deploying a new spack environment](https://docs.e3sm.org/polaris/main/developers_guide/deploying_spack.html) page of the dev guide. I also added a link to the mache documentation, which didn't exist when this was originally written. 
Checklist
> Fix docs typos and add link to mache docs

- deploy/default.cfg
- deploy/shared.py
- docs/developers_guide/ocean/index.md
- docs/developers_guide/ocean/tasks/ice_shelf_2d.md
- docs/developers_guide/organization/tasks.md
- docs/developers_guide/quick_start.md
- polaris/ocean/tasks/internal_wave/viz.py
I noticed these compass references needed to be updated.
Checklist
> Change references from `compass` to `polaris`

- deploy/bootstrap.py
`check_env()` fails when trying to run `polaris clean` because it's a deprecated command. I just removed this call from the check.
Checklist
> Remove `polaris clean` from check polaris commands

- polaris/model_step.py
- polaris/ocean/tasks/manufactured_solution/forward.py
- polaris/yaml.py
With this update, we treat config options from files (with sections) differently from replacement options provided in a dictionary in code.
This merge also explicitly converts some model config options to floats.  This seems to be necessary because the yaml parser doesn't understand numpy scalars.
Checklist
> Fix how yaml model config options are update 

- .github/workflows/build_workflow.yml
- deploy/conda-dev-spec.template
- deploy/default.cfg
- docs/users_guide/quick_start.md
- setup.cfg
Python 3.12 is now supported by `conda-forge`, and thus I've added it to polaris in this PR.
Checklist
> Add support for python 3.12

- .github/workflows/build_workflow.yml
- .github/workflows/docs_workflow.yml
In this PR I made a few tweaks to the behavior of the CI workflows. These changes are:
1. `cancel_others` is now set to false by default, which should make it easier to decipher if a bug is isolated to a specific version of python via CI
2. The `defaults` channel has been removed as we can now exclusively use `conda-forge`
3. The timeout for the `pre-commit` job has been upped to 5 minutes
> Tweak behavior of CI workflows

- configure_polaris_envs.py
- deploy/bootstrap.py
- docs/developers_guide/quick_start.md
In this PR I added a new flag to the `python -m pip install [-e] .` command. `--no-build-isolation` indicates that pip should not install build time dependencies from PyPi.
Checklist
> Add additional flags to `pip install` command in docs and deployment

- polaris/yaml.py
> Set default model for mpas_to_yaml to mpas-ocean

- docs/developers_guide/framework/model.md
- docs/developers_guide/ocean/api.md
- docs/developers_guide/organization/steps.md
- docs/tutorials/dev_add_test_group.md
- polaris/ocean/convergence/forward.py
- polaris/ocean/ice_shelf/__init__.py
- polaris/ocean/ice_shelf/ssh_forward.py
- polaris/ocean/model/ocean_model_step.py
- polaris/ocean/tasks/baroclinic_channel/decomp/__init__.py
- polaris/ocean/tasks/baroclinic_channel/default/__init__.py
- polaris/ocean/tasks/baroclinic_channel/forward.py
- polaris/ocean/tasks/baroclinic_channel/restart/__init__.py
- polaris/ocean/tasks/baroclinic_channel/restart/restart_step.py
- polaris/ocean/tasks/baroclinic_channel/threads/__init__.py
- polaris/ocean/tasks/cosine_bell/forward.py
- polaris/ocean/tasks/geostrophic/forward.py
- polaris/ocean/tasks/ice_shelf_2d/default/__init__.py
- polaris/ocean/tasks/ice_shelf_2d/forward.py
- polaris/ocean/tasks/inertial_gravity_wave/forward.py
- polaris/ocean/tasks/internal_wave/default/__init__.py
- polaris/ocean/tasks/internal_wave/forward.py
- polaris/ocean/tasks/internal_wave/rpe/__init__.py
- polaris/ocean/tasks/manufactured_solution/forward.py
- polaris/ocean/tasks/manufactured_solution/init.py
- polaris/ocean/tasks/sphere_transport/forward.py
Include graph partition file only when the ocean model is MPAS-Ocean so there aren't unnecessary files in Omega tests.
Checklist
> Fixup partition file presence

- docs/developers_guide/framework/visualization.md
- docs/developers_guide/ocean/tasks/correlated_tracers_2d.md
- docs/developers_guide/ocean/tasks/divergent_2d.md
- docs/developers_guide/ocean/tasks/nondivergent_2d.md
- docs/developers_guide/ocean/tasks/rotation_2d.md
- polaris/ocean/tasks/sphere_transport/sphere_transport.cfg
- polaris/viz/spherical.py
Add options for over/under colors for the colormap used in spherical mpas visualization. These were added to be able to more conveniently visualize over and undershoots in the tracer advection scheme tested in the `sphere_transport` tests.
> Enhance spherical tracer transport test viz

- polaris/ocean/tasks/cosine_bell/forward.py
- polaris/ocean/tasks/geostrophic/forward.py
- polaris/ocean/tasks/sphere_transport/forward.py
This PR corrects a small bug introduced by https://github.com/E3SM-Project/polaris/pull/225. When inputs are cached, we need to point to the mesh step rather than the init step for the graph files. Doesn't hurt to point to the mesh step when inputs are not cached either.
> Fixup graph paths for cached inputs

- polaris/ocean/convergence/convergence.cfg
- polaris/ocean/tasks/manufactured_solution/__init__.py
- polaris/ocean/tasks/manufactured_solution/manufactured_solution.cfg
In the `manufactured_solution` test, this needs to be `RungeKutte4`.  (I'm not worrying about other tests yet.)
Checklist
> Set default `time_integrator` for Omega

- deploy/conda-dev-spec.template
- docs/conf.py
This merge removes `myst-to-rst` (which is not being maintained) and constrain sphinx to newer versions (>= 7.0.0).
It also includes some cleanup of the config script for the docs, including removing unused imports and removing an unneeded path to the read-the-docs theme files.
> Clean up the docs

- docs/developers_guide/framework/model.md
- docs/developers_guide/ocean/api.md
- docs/developers_guide/ocean/framework.md
- polaris/ocean/convergence/analysis.py
- polaris/ocean/model/__init__.py
- polaris/ocean/model/mpaso_to_omega.yaml
- polaris/ocean/model/ocean_io_step.py
- polaris/ocean/model/ocean_model_step.py
- polaris/ocean/tasks/manufactured_solution/analysis.py
- polaris/ocean/tasks/manufactured_solution/init.py
- polaris/ocean/tasks/manufactured_solution/viz.py
> Add map between MPAS-Ocean and Omega variables

- polaris/ocean/convergence/forward.py
- polaris/ocean/tasks/manufactured_solution/__init__.py
This PR uses a mapping between MPAS-O and Omega time integrator namelist options in the convergence forward step rather than in the manufactured solution test case. As more non-convergence Omega tests and supported Omega time integration schemes are added, this mapping may be moved.
> Map time integrator for convergence tests

- deploy/conda-dev-spec.template
We will need to use system git, as the conda-forge version brings in perl, which interferes with Omega's build system.
> Remove git from polaris environment

- utils/omega/ctest/README.md
There is a small typo in the ctest path which causes copying and pasting the command from the README to break.
Checklist
> Fix small typo in ctest path

- pyproject.toml
This PR revises the previous author list to one that includes all contributors to Polaris on GitHub.
> Add list of authors to `pyproject.toml`

- deploy/bootstrap.py
- deploy/conda-dev-spec.template
- deploy/default.cfg
- polaris/version.py
- pyproject.toml
- esmf v8.7.0
- geometric_features v1.5.0
- mache v1.27.0
- moab from master branch (spack only) -- brings in unreleased features needed for high res cubed-sphere to MPAS mesh remapping
- mpas_tools v0.36.0 -- adds function for computing barotropic streamfunction
MPAS-Ocean with `pr`:
Omega CTests:
MPAS-Ocean with `pr`:
Omega CTests:
> Update to v0.5.0-alpha.1

- polaris/model_step.py
- polaris/ocean/convergence/forward.py
- polaris/ocean/model/mpaso_to_omega.yaml
- polaris/ocean/model/ocean_io_step.py
- polaris/ocean/model/ocean_model_step.py
- polaris/ocean/tasks/manufactured_solution/forward.py
- polaris/ocean/tasks/manufactured_solution/forward.yaml
- polaris/ocean/tasks/manufactured_solution/manufactured_solution.cfg
- polaris/yaml.py
This merge adds the capability to only copy streams from the Omega `Default.yml` file if they are explicitly requested by a given test case.
Here, we also update the map of variables between MPAS-Ocean and Omega, and add placeholders for mapping dimension names once the new Omega names are fully supported.  (See https://github.com/E3SM-Project/Omega/issues/172).
This merge updates the manufactured solution test case to support Omega in all steps but `analysis` (which requires further development of the time variable, see https://github.com/E3SM-Project/Omega/pull/169).
Checklist
> Updates related to Omega IOStreams

- polaris/mpas/__init__.py
- polaris/mpas/time.py
- polaris/ocean/convergence/analysis.py
- polaris/ocean/tasks/manufactured_solution/viz.py
This merge fixes the manufactured solution analysis task in Omega by using the `time` coordinate instead of the MPAS-Ocean `xtime` variable.
It also attempts to use `time` in the viz step but testing is currently inhibited by #248 
Checklist
> Support the Omega `time` coordinate

- polaris/ocean/tasks/cosine_bell/analysis.py
- polaris/ocean/tasks/cosine_bell/cosine_bell.cfg
- polaris/ocean/tasks/cosine_bell/forward.py
- polaris/ocean/tasks/cosine_bell/forward.yaml
- polaris/ocean/tasks/cosine_bell/init.py
- polaris/ocean/tasks/cosine_bell/viz.py
> Add Omega support to Cosine Bell tests

- docs/developers_guide/framework/validation.md
- docs/developers_guide/ocean/api.md
- docs/developers_guide/ocean/tasks/cosine_bell.md
- docs/users_guide/ocean/tasks/cosine_bell.md
- polaris/ocean/convergence/__init__.py
- polaris/ocean/suites/cosine_bell.txt
- polaris/ocean/suites/cosine_bell_cached_init.txt
- polaris/ocean/suites/nightly.txt
- polaris/ocean/suites/pr.txt
- polaris/ocean/tasks/cosine_bell/__init__.py
- polaris/ocean/tasks/cosine_bell/forward.py
- polaris/ocean/tasks/cosine_bell/forward.yaml
- polaris/ocean/tasks/cosine_bell/restart/__init__.py
- polaris/ocean/tasks/cosine_bell/restart/forward.yaml
- polaris/ocean/tasks/cosine_bell/restart/restart_step.py
- polaris/ocean/tasks/cosine_bell/restart/validate.py
- polaris/ocean/tasks/cosine_bell/validate.py
- polaris/ocean/tasks/manufactured_solution/forward.yaml
- polaris/validate.py
This merge adds a restart test to the cosine bell configuration.  This requires some changes to the validation framework for comparing variables to support the translation that Polaris performs between Omega native dimension and variable names and those for MPAS-Ocean that the Polaris ocean component uses generally.
A small amount of related cleanup is also included.
Checklist
> Add a restart test to cosine bell

- docs/conf.py
- docs/developers_guide/ocean/api.md
- docs/developers_guide/ocean/tasks/barotropic_gyre.md
- docs/developers_guide/ocean/tasks/cosine_bell.md
- docs/tutorials/dev_add_test_group.md
- docs/users_guide/ocean/suites.md
- docs/users_guide/ocean/tasks/cosine_bell.md
- polaris/ocean/suites/cosine_bell.txt
- polaris/ocean/suites/nightly.txt
- polaris/ocean/suites/omega_pr.txt
- polaris/ocean/suites/pr.txt
- polaris/ocean/tasks/cosine_bell/__init__.py
- polaris/ocean/tasks/cosine_bell/decomp.py
> Add a cosine-bell decomposition test

- .github/workflows/build_workflow.yml
- .pre-commit-config.yaml
This PR makes a few changes to the `pre-commit` configuration file and the `pre-commit` steps in the build CI workflow. I also did some minor cleanup to the build workflow.
Changes:
1. Added an argument to the build workflow python version matrix to not cancel other jobs when a job fails for a specific python version.
2. Added a check that locates the files with changes and runs `pre-commit` only on those files.
3. Updated `pre-commit` by running `pre-commit autoupdate`
4. Cleaned up an unnecessary comment in the build workflow.
Checklist
> Pre-commit updates and fixes

- docs/users_guide/ocean/tasks/manufactured_solution.md
- polaris/ocean/convergence/analysis.py
- polaris/ocean/suites/convergence.txt
- polaris/ocean/suites/manufactured_solution.txt
- polaris/ocean/tasks/manufactured_solution/__init__.py
- polaris/ocean/tasks/manufactured_solution/forward.py
- polaris/ocean/tasks/manufactured_solution/forward.yaml
- polaris/ocean/tasks/manufactured_solution/init.py
- polaris/ocean/tasks/manufactured_solution/manufactured_solution.cfg
- polaris/ocean/tasks/manufactured_solution/viz.py
This PR adds manufactured solution tests for del2 and del4 and renames the existing case to `default`. Both del2 and del4 tests depend on the corresponding source terms being added to the model. These terms are added to MPAS-Ocean here https://github.com/E3SM-Ocean-Discussion/E3SM/pull/110. All tests depend on https://github.com/E3SM-Ocean-Discussion/E3SM/pull/55 to achieve expected convergence. 
Checklist
> Extend manufactured solution to del2 and del4

- deploy/bootstrap.py
As noted in #252, the configure script was not setting the group of deployed environments to `e3sm`. This was due to an object being passed incorrectly through a decorator. I've fixed the issue in this PR.
Checklist
closes #252
> Fix directory permissions not being updated

- deploy/conda-dev-spec.template
There seems to be an issue with hvplot and bokeh with the latest dask:
```
WARNING:param.hvplot_extension: bokeh backend hook <function _load_bokeh at 0x7fb7511e7e20> failed with following exception: module 'dask.dataframe.core' has no attribute 'DataFrame'
```
Checklist
> Temporarily constrain dask

- polaris/ocean/config/single_layer.yaml
- polaris/ocean/convergence/analysis.py
- polaris/ocean/suites/omega_pr.txt
- polaris/ocean/tasks/sphere_transport/analysis.py
- polaris/ocean/tasks/sphere_transport/correlated_tracers_2d.cfg
- polaris/ocean/tasks/sphere_transport/divergent_2d.cfg
- polaris/ocean/tasks/sphere_transport/forward.py
- polaris/ocean/tasks/sphere_transport/forward.yaml
- polaris/ocean/tasks/sphere_transport/init.py
- polaris/ocean/tasks/sphere_transport/nondivergent_2d.cfg
- polaris/ocean/tasks/sphere_transport/rotation_2d.cfg
- polaris/ocean/tasks/sphere_transport/sphere_transport.cfg
- polaris/ocean/tasks/sphere_transport/viz.py
Add omega support for the `sphere_transport` test suite
Checklist
> Add support for omega sphere transport tests

- polaris/ocean/tasks/inertial_gravity_wave/__init__.py
- polaris/ocean/tasks/inertial_gravity_wave/forward.yaml
- polaris/ocean/tasks/inertial_gravity_wave/viz.py
The `viz` step didn't get updated when we added refinement in just space and just time separately, so that is the main fix here.  The `viz` step is now more similar to the manufactured solution step, which was fixed in #250.
This merge also sets the namelist option `config_disable_tr_all_tend = .true.`, which was correctly dropped from the `single_layer.yaml` in #262 but which now is correctly included in this test's `forward.yaml`.
Checklist
> Fix inertial gravity wave test

- deploy/conda-dev-spec.template
- polaris/version.py
It has introduced syntax that is not compatible with python 3.9.
This requires updating to v0.5.0-alpha.2, since a dependency has changed.
Checklist
See https://github.com/UXARRAY/uxarray/issues/1133
> Exclude latest uxarray 2025.01.0 

- polaris/ocean/convergence/__init__.py
- polaris/ocean/tasks/cosine_bell/__init__.py
- polaris/ocean/tasks/cosine_bell/decomp.py
- polaris/ocean/tasks/cosine_bell/restart/__init__.py
These need to come from the spherical values, not the planar ones.
In the process, I cleaned up the cosine bell a little bit by switching it to use only `prefix` and not the `icosahedral` boolean.
Finally, this merge fixes a bug in the split-explicit computation of time steps.  There is a for-loop over refinement factors that I don't think should be there.
Checklist
Fixes #257
> Fix refinement factors in cosine bell

- .github/workflows/build_workflow.yml
- .github/workflows/docs_workflow.yml
- deploy/conda-dev-spec.template
- deploy/default.cfg
- docs/users_guide/quick_start.md
- pyproject.toml
This PR updates the supported python versions for `polaris` to 3.10-3.13 to accommodate the `mosaic` package. Thus, this PR will be merged in when #256 is merged. 
Checklist
> Drop support for Python 3.9 and add support for Python 3.13

- polaris/viz/spherical.py
Colormap over/under settings from config files were not being used for spherical viz. Omega submodule is also updated.
Checklist
> Fix colormap limits for spherical viz

- polaris/ocean/tasks/cosine_bell/forward.yaml
- polaris/ocean/tasks/manufactured_solution/forward.yaml
- polaris/ocean/tasks/sphere_transport/forward.yaml
This merge Updates `manufactured_solution`, `cosine_bell` and `sphere_transport` tests to support time-slice capabilities brought in by https://github.com/E3SM-Project/Omega/pull/189
Some incorrect task names in the `omega_pr`suite have also been fixed.
Checklist
> Update tests to support Omega time slices

- utils/omega/ctest/README.md
This PR just adds a line in the README about the `--account` argument you might need to specify when running the CTest utility.
Checklist
> Add `--account` to CTest instructions

- polaris/viz/planar.py
We can't pass `vmin` and `vmax` along with `norm` that also tried to define the min and max:
```
ValueError: Passing a Normalize instance simultaneously with vmin/vmax is not supported.  Please pass vmin/vmax directly to the norm when creating it.
```
This merge also drops an attempt to keep `vmin` positive for log norm, instead requiring the calling code to set reasonable bounds for log plots.
Checklist
> Fix planar plots with log norm

- .github/workflows/build_workflow.yml
- .github/workflows/docs_workflow.yml
- deploy/shared.py
This PR switches CI to use the `setup-micromamba` GitHub action instead of the `setup-miniconda` GitHub action, in an effort to fix CI crashes caused by the latest `miniconda` version. 
To do this, I needed to make a change to `deploy.shared`, so that it did not reference the `CONDA_EXE` variable. Apparently miniconda sets this environment var, but micromamba does not. 
Checklist
> Switch CI from miniconda to micromamba

- polaris/remap/mapping_file_step.py
In the `MappingFileStep`, it is important that we make not just the scrip files but also the mapping file itself have an absolute path so other steps that have the mapping step as a dependency can find the mapping file.  Otherwise, they unnecessarily recreated it (and do so without proper logging).
Checklist
> Make mapping filename an absolute path

- docs/developers_guide/e3sm/init/tasks/topo.md
- polaris/e3sm/init/cached_files.json
- polaris/tasks/e3sm/init/add_tasks.py
- polaris/tasks/e3sm/init/topo/combine/combine.cfg
- polaris/tasks/e3sm/init/topo/combine/combine_low_res.cfg
- polaris/tasks/e3sm/init/topo/combine/step.py
- polaris/tasks/e3sm/init/topo/combine/steps.py
- polaris/tasks/e3sm/init/topo/combine/task.py
- polaris/tasks/e3sm/init/topo/combine/viz.py
This is needed for efficiency for coarser (e.g. Icos240) MPAS meshes.
The results from the low-res step have also been cached for more efficient use in other `e3sm/init` workflows.
This merge also fixes an issue with the shared config file for the combine-topo steps.  Previously, the task and step were using different config files, whereas with this fix, they use a single, shared config file as intended.
It also fixes a bug with the approach for caching combined topography.  We can't simply cache it by setting the `cached` attribute at construction, we need to set it in specific tasks at setup.
Checklist
> Add a step for combining topography at low res (ne120)

- polaris/viz/spherical.py
This should make multiple plots with the same spherical MPAS mesh and projection much more efficient.
Checklist
> Allow reuse of mosaic descriptor in spherical plots

- polaris/tasks/ocean/sphere_transport/filament_analysis.py
- polaris/tasks/ocean/sphere_transport/mixing_analysis.py
It appears there is only a single vertical level but the analysis was attempting to index vertical level 1.
Checklist
> Fix `zidx` in `sphere_transport` analysis

- deploy/default.cfg
- docs/developers_guide/framework/model.md
- docs/developers_guide/organization/steps.md
- docs/users_guide/ocean/tasks/overflow.md
- docs/users_guide/ocean/tasks/template.md
- polaris/default.cfg
- polaris/mesh/spherical.py
- polaris/model_step.py
- polaris/streams.py
- polaris/version.py
This is E3SM's preferred fromat for large files.  Since E3SM can't support `NETCDF4` format, it is the only option that we
can be sure will work for both small and large meshes, and saves us the hassle of having different fromats for different mesh sizes.
Good performance does require first writing a `NETCDF4` file from `xarray` and then converting to `NETCDF3_64BIT_DATA`.  This is handled by a new version of `mpas_tools`, see https://github.com/MPAS-Dev/MPAS-Tools/pull/633.
This pull request introduces changes to improve NetCDF file handling and streamline the codebase in `polaris`. Key updates include modifying the default NetCDF format, refactoring imports for clarity, and adding functionality to set default I/O types for streams. Below is a breakdown of the most important changes:
* …
> Switch to writing files in CDF5 (`NETCDF3_64BIT_DATA`) format 

- polaris/tasks/ocean/barotropic_gyre/init.py
The inequality on the horizontal resolution check for the barotropic gyre test case was reversed. This PR fixes that bug.
> Fix a bug in the resolution limit given in the barotropic gyre case

- .pre-commit-config.yaml
The `pre-commit` hook used to be `ruff` but it changed to `ruff-check`, resulting in a message about the legacy alias. This updates the hook to the current `ruff-check` format.
Checklist
> Change `pre-commit` hook ID to `ruff-check`

- polaris/mesh/base/add.py
The prefixes in the check need to be lowercase.
Missed in #359.
Checklist
> Fix assigning resolution for fixed-res base meshes

- deploy/default.cfg
- polaris/version.py
- utils/omega/ctest/build_and_ctest.template
- utils/omega/ctest/omega_ctest.py
- esmf v8.9.0
- mache v1.32.0 -- brings in a fix to the libfabric module on Perlmutter
- moab master -- brings in bug fix related to remapping from cubed-sphere grids to MPAS meshes
- scorpio v1.8.2
Drops python 3.9, which has been dropped by conda-forge.
This merge includes various fixes to the Omega CTest utility needed to get it working with the latest Omega/develop.
MPAS-Ocean with `pr`:
Omega CTests:
MPAS-Ocean with `pr`:
Omega CTests:
> Update to 0.9.0 alpha.1
